# Generated by Django 2.1.11 on 2019-08-21 15:05

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerFolder',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('style', models.CharField(choices=[('list', 'List'), ('slideshow', 'Slideshow')], default='list', max_length=50, verbose_name='Style')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_folder_filerfolder', serialize=False, to='cms.CMSPlugin')),
                ('folder', filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Folder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
