# Generated by Django 2.1.11 on 2019-08-21 15:05

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerFile',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('target_blank', models.BooleanField(default=False, verbose_name='Open link in new window')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='Style')),
                ('link_attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, help_text='Optional. Adds HTML attributes to the rendered link.')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_file_filerfile', serialize=False, to='cms.CMSPlugin')),
                ('file', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
