# Generated by Django 2.1.11 on 2019-08-21 15:05

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerImage',
            fields=[
                ('style', models.CharField(blank=True, default='', max_length=50, verbose_name='Style')),
                ('caption_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='caption text')),
                ('image_url', models.URLField(blank=True, default=None, null=True, verbose_name='alternative image url')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text')),
                ('use_original_image', models.BooleanField(default=False, help_text='do not resize the image. use the original image instead.', verbose_name='use the original image')),
                ('use_autoscale', models.BooleanField(default=False, help_text='tries to auto scale the image based on the placeholder context', verbose_name='use automatic scaling')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('crop', models.BooleanField(default=True, verbose_name='crop')),
                ('upscale', models.BooleanField(default=True, verbose_name='upscale')),
                ('alignment', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], max_length=10, null=True, verbose_name='image alignment')),
                ('free_link', models.CharField(blank=True, help_text='if present image will be clickable', max_length=2000, null=True, verbose_name='link')),
                ('original_link', models.BooleanField(default=False, help_text='if present image will be clickable', verbose_name='link original image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('target_blank', models.BooleanField(default=False, verbose_name='Open link in new window')),
                ('link_attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, help_text='Optional. Adds HTML attributes to the rendered link.')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_image_filerimage', serialize=False, to='cms.CMSPlugin')),
                ('file_link', filer.fields.file.FilerFileField(blank=True, default=None, help_text='if present image will be clickable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.File', verbose_name='file link')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('page_link', cms.models.fields.PageField(blank=True, help_text='if present image will be clickable', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='page link')),
                ('thumbnail_option', models.ForeignKey(blank=True, help_text='overrides width, height, crop and upscale with values from the selected thumbnail option', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='thumbnail option')),
            ],
            options={
                'verbose_name': 'filer image',
                'verbose_name_plural': 'filer images',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
